## This configuration was generated by terraform-provider-oci

resource oci_core_nat_gateway export_NAT_gw {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-05-26T23:53:13.342Z"
  }
  display_name = "NAT_gw"
  freeform_tags = {
  }
  public_ip_id = "ocid1.publicip.oc1.iad.aaaaaaaagf7vfymb2vvobu5s2375d3zf64olntlxhb4tptyetvbepmsixcwa"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn_test.id
}

resource oci_core_drg_attachment export_drg_attach_vcn2 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-08T16:13:38.011Z"
  }
  display_name       = "drg_attach_vcn2"
  drg_id             = oci_core_drg.export_DRG1.id
  drg_route_table_id = oci_core_drg.export_DRG1.default_drg_route_tables[0].vcn
  #export_drg_route_distribution_id = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  network_details {
    id = oci_core_vcn.export_vcn_test_2.id
    #route_table_id = <<Optional value not found in discovery>>
    type           = "VCN"
    vcn_route_type = "SUBNET_CIDRS"
  }
  #remove_export_drg_route_distribution_trigger = <<Optional value not found in discovery>>
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn_test_2.id
}

resource oci_core_drg_attachment export_vcn_test_attach {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-08T16:08:45.640Z"
  }
  display_name       = "vcn_test_attach"
  drg_id             = oci_core_drg.export_DRG1.id
  drg_route_table_id = oci_core_drg.export_DRG1.default_drg_route_tables[0].vcn
  #export_drg_route_distribution_id = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  network_details {
    id = oci_core_vcn.export_vcn_test.id
    #route_table_id = <<Optional value not found in discovery>>
    type           = "VCN"
    vcn_route_type = "SUBNET_CIDRS"
  }
  #remove_export_drg_route_distribution_trigger = <<Optional value not found in discovery>>
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn_test.id
}

resource oci_core_drg export_DRG1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-03T16:34:00.423Z"
  }
  display_name = "DRG1"
  freeform_tags = {
  }
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-vcn_test_2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-05T23:53:44.992Z"
  }
  display_name     = "Default DHCP Options for vcn_test_2"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = "ocid1.dhcpoptions.oc1.iad.aaaaaaaaajiuyrpef5x2orxonoqrno53n3yl3spqeo6xwxgifoiegp23up6a"
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcntest2.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-vcn_test {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-05-21T17:21:18.586Z"
  }
  display_name     = "Default DHCP Options for vcn_test"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = "ocid1.dhcpoptions.oc1.iad.aaaaaaaa5ezxr5wpw6sd3leeamytubpigjbgff2kkj36br6vgvz5p5mzxdga"
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcntest.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_internet_gateway export_igw_2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-08T17:06:00.578Z"
  }
  display_name = "igw_2"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn_test_2.id
}

resource oci_core_internet_gateway export_igw_test {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-05-22T17:12:08.693Z"
  }
  display_name = "igw_test"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_vcn_test.id
}

resource oci_core_subnet export_public_subnet2 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "192.168.200.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-08T16:49:30.566Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-vcn_test_2.id
  display_name    = "public_subnet2"
  dns_label       = "publicsubnet2"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "192.168.200.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_vcn_test_2.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_vcn_test_2.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcn_test_2.id
}

resource oci_core_subnet export_subnet_test2 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "192.168.100.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-06T00:13:22.069Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-vcn_test_2.id
  display_name    = "subnet_test2"
  dns_label       = "subnettest2"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "192.168.100.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_rt_private2.id
  security_list_ids = [
    oci_core_vcn.export_vcn_test_2.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcn_test_2.id
}

resource oci_core_subnet export_subnet_public {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.2.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-03T14:35:09.982Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-vcn_test.id
  display_name    = "subnet_public"
  dns_label       = "subnetpublic"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "10.0.2.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_vcn_test.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_vcn_test.default_security_list_id,
    oci_core_security_list.export_security_list_public.id,
  ]
  vcn_id = oci_core_vcn.export_vcn_test.id
}

resource oci_core_subnet export_subnet_private {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-03T14:27:49.168Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-vcn_test.id
  display_name    = "subnet_private"
  dns_label       = "subnetprivate"
  freeform_tags = {
  }
  ipv4cidr_blocks = [
    "10.0.1.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_rt_private.id
  security_list_ids = [
    oci_core_security_list.export_security_list_private_network.id,
  ]
  vcn_id = oci_core_vcn.export_vcn_test.id
}

resource oci_core_vcn export_vcn_test_2 {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "192.168.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-05T23:53:44.992Z"
  }
  display_name = "vcn_test_2"
  dns_label    = "vcntest2"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
  security_attributes = {
  }
}

resource oci_core_vcn export_vcn_test {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-05-21T17:21:18.586Z"
  }
  display_name = "vcn_test"
  dns_label    = "vcntest"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
  security_attributes = {
  }
}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-ALL-routes {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for ALL routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG1.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-VCN-Routes {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for VCN Routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG1.id
  freeform_tags = {
  }
}

resource oci_core_default_drg_route_table export_Autogenerated-Drg-Route-Table-for-VCN-attachments {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-03T16:34:00.423Z"
  }
  display_name = "Autogenerated Drg Route Table for VCN attachments"
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-ALL-routes.id
  is_ecmp_enabled                  = "false"
  manage_default_resource_id       = oci_core_drg.export_DRG1.default_drg_route_tables[0].vcn
  #remove_import_trigger = <<Optional value not found in discovery>>
}

resource oci_core_default_drg_route_table export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-03T16:34:00.423Z"
  }
  display_name = "Autogenerated Drg Route Table for RPC, VC, and IPSec attachments"
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-VCN-Routes.id
  is_ecmp_enabled                  = "false"
  manage_default_resource_id       = oci_core_drg.export_DRG1.default_drg_route_tables[0].virtual_circuit
  #remove_import_trigger = <<Optional value not found in discovery>>
}

resource oci_core_default_security_list export_Default-Security-List-for-vcn_test_2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-05T23:53:44.992Z"
  }
  display_name = "Default Security List for vcn_test_2"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "allow me"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "96.231.17.60/32"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "10.0.2.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_test_2.default_security_list_id
}

resource oci_core_security_list export_security_list_public {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-03T14:40:52.886Z"
  }
  display_name = "security_list_public"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "96.231.17.60/32"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "192.168.200.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_vcn_test.id
}

resource oci_core_security_list export_security_list_private_network {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-05-26T19:34:05.976Z"
  }
  display_name = "security_list_private_network"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "allow lb"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.1.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "allow myself for initial set up and deployment of apache"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "96.231.17.60/32"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "10.0.2.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "allow myself for initial set up and deployment of apache"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "96.231.17.60/32"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "allow lb"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.1.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "192.168.100.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "192.168.100.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "1"
    source      = "192.168.100.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_vcn_test.id
}

resource oci_core_default_security_list export_Default-Security-List-for-vcn_test {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-05-21T17:21:18.586Z"
  }
  display_name = "Default Security List for vcn_test"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.1.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.2.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "allow me"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "96.231.17.60/32"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "allow me"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "96.231.17.60/32"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "allow me"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "96.231.17.60/32"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_test.default_security_list_id
}

resource oci_core_route_table export_rt_public {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-08T21:13:06.119Z"
  }
  display_name = "rt_public"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_igw_2.id
    route_type        = "STATIC"
  }
  vcn_id = oci_core_vcn.export_vcn_test_2.id
}

resource oci_core_route_table export_rt_private2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-08T21:11:13.440Z"
  }
  display_name = "rt_private2"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "10.0.1.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_drg.export_DRG1.id
    route_type        = "STATIC"
  }
  vcn_id = oci_core_vcn.export_vcn_test_2.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-vcn_test_2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-06-05T23:53:44.992Z"
  }
  display_name = "Default Route Table for vcn_test_2"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_test_2.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_igw_2.id
    route_type        = "STATIC"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "10.0.2.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_drg.export_DRG1.id
    route_type        = "STATIC"
  }
}

resource oci_core_route_table export_rt_private {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-05-26T23:57:09.869Z"
  }
  display_name = "rt_private"
  freeform_tags = {
  }
  route_rules {
    description       = "route to other VCN"
    destination       = "192.168.100.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_drg.export_DRG1.id
    route_type        = "STATIC"
  }
  vcn_id = oci_core_vcn.export_vcn_test.id
}

resource oci_core_route_table export_public_route_table {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-05-28T19:07:51.082Z"
  }
  display_name = "public_route_table"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_igw_test.id
    route_type        = "STATIC"
  }
  vcn_id = oci_core_vcn.export_vcn_test.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-vcn_test {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ramon.smith0902@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-05-21T17:21:18.586Z"
  }
  display_name = "Default Route Table for vcn_test"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_vcn_test.default_route_table_id
  route_rules {
    description       = "route for public subnet to reach the internet"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_igw_test.id
    route_type        = "STATIC"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "192.168.200.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_drg.export_DRG1.id
    route_type        = "STATIC"
  }
}

